{% set version = "0.5.2" %}

package:
  name: visualpic
  version: {{ version }}

source:
  url: https://github.com/AngelFP/VisualPIC/archive/refs/tags/{{ version }}.tar.gz
  sha256: 9b0fc6f47f1321ad0a49bf8c2cd81ee35f0827b3420cc741ce72b43fd3f2b7a4

build:
  number: 1
  noarch: python
  entry_points:
    - vpic = visualpic.cli.vpic:vpic
    - vpic3d = visualpic.cli.vpic3d:vpic3d
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - aptools
    - h5py
    - matplotlib-base
    - numpy
    - openpmd-viewer
    - python >={{ python_min }}
    - pyvista
    - pyqt
    - scipy
    - tqdm
    - vtk

test:
  requires:
    - python {{ python_min }}
  imports:
    - visualpic

about:
  home: https://github.com/AngelFP/VisualPIC/tree/dev/examples
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  summary: Data Visualization for Particle-in-Cell Codes

  description: |
    VisualPIC - Data Visualization for Particle-in-Cell Codes.
  dev_url: https://github.com/AngelFP/VisualPIC

extra:
  recipe-maintainers:
    - AngelFP
    - ax3l
